version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - echo Starting Maven build process...
      - mvn clean
  build:
    commands:
      - echo Building JAR with Maven...
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/*.jar
  discard-paths: yes